post:
  operationId: saveFeatureConfiguration
  summary: Save Feature Configuration
  description: Save feature configuration (enables or disables pre-defined optional search options)
  tags:
    - config
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../../schemas/entity/featureConfig.yaml'
        examples:
          createRequest:
            $ref: '../../examples/request/updateCreateFeatureRequest.yaml'
  responses:
    '200':
      description: Language support has been added.
      content:
        application/json:
          schema:
            $ref: '../../schemas/entity/featureConfig.yaml'
          examples:
            createResponse:
              $ref: '../../examples/response/updateFeatureResponse.yaml'
    '400':
      $ref: '../../responses/badRequestResponse.yaml'
    '422':
      $ref: '../../responses/unprocessableEntityResponse.yaml'
get:
  operationId: getAllFeatures
  summary: Get Feature Configurations
  description: Get all feature configurations per tenant
  tags:
    - config
  responses:
    '200':
      description: All feature configurations
      content:
        application/json:
          schema:
            $ref: '../../schemas/entity/featureConfigs.yaml'
          examples:
            allFeaturesResponse:
              value:
                features:
                  - feature: "search.all.fields"
                    enabled: false
                totalRecords: 1
