version: "3.8"

services:
  mod-search:
    container_name: mod-search
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - mod-search-local
    ports:
      - "8081:8081"
      - "5010:5010"
    depends_on:
      - api-mock
    environment:
      DB_HOST: db
      JAVA_OPTIONS: -Xmx120m -Xms120m
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,address=*:5010,server=y,suspend=n
      okapi.url: http://api-mock:8080

  api-mock:
    image: wiremock/wiremock:2.32.0
    container_name: api-mock
    networks:
      - mod-search-local
    command:
      - "--verbose"
    ports:
      - "9130:8080"
    volumes:
      - ./src/test/resources/mappings:/home/wiremock/mappings

  elasticsearch:
    container_name: elasticsearch
    image: opensearch-it:1.3.2
    build:
      context: docker/elasticsearch
      dockerfile: Dockerfile
    networks:
      - mod-search-local
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - discovery.zen.minimum_master_nodes=1
      - "DISABLE_SECURITY_PLUGIN=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  opensearch-dashboards:
    container_name: opensearch-dashboards
    image: opensearch-dashboards-it:1.3.2
    build:
      context: docker/dashboards
      dockerfile: Dockerfile
    ports:
      - "5601:5601"
    environment:
      OPENSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    networks:
      - mod-search-local
    depends_on:
      - elasticsearch

  zookeeper:
    image: zookeeper:3.6.2
    container_name: zookeeper
    networks:
      - mod-search-local
    ports:
      - "2181:2181"
      - "8080:8080"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOO_PORT_NUMBER: 2181

  kafka:
    image: wurstmeister/kafka:2.13-2.6.0
    container_name: kafka
    hostname: kafka
    networks:
      - mod-search-local
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:29092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://localhost:29092
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_MESSAGE_MAX_BYTES: 1000000
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

  db:
    container_name: db
    image: postgres:13.4-alpine
    networks:
      - mod-search-local
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: okapi_modules

networks:
  mod-search-local:
    driver: bridge

volumes:
  es-data: { }
  db-data: { }
