openapi: 3.0.0
info:
  title: Search API
  version: v2.1.0
  description: |
    API for searching, browsing, and managing facets for various record types, including instances, holdings, and authorities.
    It also provides endpoints for configuring search and browse features, as well as managing the search index.
  contact:
    name: Spitfire team

servers:
  - url: https://{environment}-okapi.ci.folio.org
    description: Development environments.
    variables:
      environment:
        default: folio-dev-spitfire
        enum:
          - folio-dev-spitfire
          - folio-perf-spitfire
  - url: https://folio-{environment}-okapi.dev.folio.org
    description: Reference environments.
    variables:
      environment:
        default: snapshot
        enum:
          - snapshot
          - snapshot-2

tags:
  - name: browse
    description: Provides endpoints to browse records (e.g., instances, authorities) in alphabetical order by a specific field, such as call number, classification number, subject, or contributor.
  - name: config
    description: Provides endpoints to configure search and browse features, such as enabling/disabling specific features or managing language settings.
  - name: facets
    description: Provides endpoints to retrieve aggregated information (facets) about records, such as counts of records by specific fields or ranges of values. This can be used for faceted search or browsing.
  - name: index-management
    description: Provides endpoints to manage the search index, including creating or updating mappings, settings, and manually populating the index with records from external sources (e.g., inventory).
  - name: search
    description: Provides endpoints to search for records (e.g., instances, authorities) using CQL (Contextual Query Language) queries. Supports various search options and retrieval of search results.
  - name: search-consortium
    description: Provides endpoints to search for consolidated records (e.g., holdings, items) across multiple institutions or libraries within a consortium.
  - name: search-resources-ids
    description: Provides endpoints to retrieve record IDs by CQL queries, without returning the full record data.

paths:
  /search/instances:
    $ref: 'paths/search-instances/search-instances.yaml'

  /search/instances/ids:
    $ref: 'paths/search-instances/search-instances-ids.yaml'

  /search/holdings/ids:
    $ref: 'paths/search-holdings/search-holdings-ids.yaml'

  /search/{recordType}/facets:
    $ref: 'paths/search-facets/search-record-type-facets.yaml'

  /search/authorities:
    $ref: 'paths/search-authorities/search-authorities.yaml'

  /search/resources/jobs/{jobId}:
    $ref: 'paths/search-resources/search-resources-jobs-job-id.yaml'

  /search/resources/jobs:
    $ref: 'paths/search-resources/search-resources-jobs.yaml'

  /search/resources/jobs/{jobId}/ids:
    $ref: 'paths/search-resources/search-resources-jobs-job-id-ids.yaml'

  /search/consortium/holdings:
    $ref: 'paths/search-consortium/search-consortium-holdings.yaml'

  /search/consortium/items:
    $ref: 'paths/search-consortium/search-consortium-items.yaml'

  /search/consortium/locations:
    $ref: 'paths/search-consortium/search-consortium-locations.yaml'

  /search/consortium/campuses:
    $ref: 'paths/search-consortium/search-consortium-campuses.yaml'

  /search/consortium/libraries:
    $ref: 'paths/search-consortium/search-consortium-libraries.yaml'

  /search/consortium/institutions:
    $ref: 'paths/search-consortium/search-consortium-institutions.yaml'

  /search/consortium/batch/items:
    $ref: 'paths/search-consortium/search-consortium-batch-items.yaml'

  /search/consortium/batch/holdings:
    $ref: 'paths/search-consortium/search-consortium-batch-holdings.yaml'

  /search/consortium/holding/{id}:
    $ref: 'paths/search-consortium/search-consortium-holding.yaml'

  /search/consortium/item/{id}:
    $ref: 'paths/search-consortium/search-consortium-item.yaml'

  /search/index/indices:
    $ref: 'paths/search-index/search-index-indices.yaml'

  /search/index/mappings:
    $ref: 'paths/search-index/search-index-mappings.yaml'

  /search/index/records:
    $ref: 'paths/search-index/search-index-records.yaml'

  /search/index/settings:
    $ref: 'paths/search-index/search-index-settings.yaml'

  /search/index/inventory/reindex:
    $ref: 'paths/search-index/search-index-inventory-reindex.yaml'

  /search/index/instance-records/reindex/status:
    $ref: 'paths/search-index/search-index-reindex-status.yaml'

  /search/index/instance-records/reindex/full:
    $ref: 'paths/reindex-instance-records/reindex-instance-records.yaml'

  /search/config/languages:
    $ref: 'paths/search-config/search-config-languages.yaml'

  /search/config/languages/{code}:
    $ref: 'paths/search-config/search-config-languages-code.yaml'

  /search/config/features:
    $ref: 'paths/search-config/search-config-features.yaml'

  /search/config/features/{featureId}:
    $ref: 'paths/search-config/search-config-features-feature-id.yaml'

  /search/linked-data/works:
    $ref: 'paths/search-linked-data/search-linked-data-works.yaml'

  /search/linked-data/authorities:
    $ref: 'paths/search-linked-data/search-linked-data-authorities.yaml'

  /browse/call-numbers/instances:
    $ref: 'paths/browse-call-numbers/browse-call-numbers-instances.yaml'

  /browse/classification-numbers/{browseOptionId}/instances:
    $ref: 'paths/browse-classification-numbers/browse-instance-classifications.yaml'

  /browse/subjects/instances:
    $ref: 'paths/browse-subject/browse-subjects-instances.yaml'

  /browse/contributors/instances:
    $ref: 'paths/browse-contributors/browse-contributors-instances.yaml'

  /browse/authorities:
    $ref: 'paths/browse-authorities/browse-authorities.yaml'

  /browse/config/{browseType}:
    $ref: 'paths/browse-config/browse-type.yaml'

  /browse/config/{browseType}/{browseOptionId}:
    $ref: 'paths/browse-config/browse-type-browse-option-id.yaml'


