description: Language config
type: object
properties:
  languageConfigs:
    type: array
    x-field-extra-annotation: "@com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)"
    description: Configured languages for a tenant
    items:
      $ref: "./languageConfig.yaml"
  totalRecords:
    type: integer
    description: Total records that matches the query.
    minimum: 0
additionalProperties: false
required:
  - languageConfigs
  - totalRecords
