package org.folio.search.model.types;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum FieldType {

  /**
   * Provides opportunity to use field values for sorting.
   */
  PLAIN("plain"),

  /**
   * Provides opportunity to use field values for faceting.
   */
  OBJECT("object"),

  /**
   * Additional field that to be generated by a processor.
   */
  SEARCH("search"),

  /**
   * Field designed for splitting entity to the multiple entities for authority resource using that the value of the
   * field as a criterion to split.
   */
  AUTHORITY("authority");

  /**
   * Json representation of enum.
   */
  @JsonValue
  private final String value;
}
