FROM opensearchproject/opensearch:1.3.1

RUN bin/opensearch-plugin install --batch \
  analysis-icu \
  analysis-kuromoji \
  analysis-smartcn \
  analysis-stempel \
  analysis-nori \
  analysis-phonetic
